### ISSUE TITLE
Waila Showing "Restricted" when item is already unlocked

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/WailaStages#1]
https://i.artdude.uk/darkosto/up3HTC13.png

MC: 1.12.2
Forge: 2575
WAWLA: 2.5.248
HWYLA: 1.8.23-B38_1.12
WAILA Stages: 1.0.22

Thank you

**Comment by Darkhax** [comment]
Was this ever fixed? Image is not visible.

**Comment by Darkosto** [comment]
Not that I saw, but I'm going to test it out tomorrow when I do pack work. I think @justinrusso is also working on the pack right now so maybe he can check it out as well.

**Comment by justinrusso** [comment]
Hm, I personally don't think I've run into that issue, but it has been reported as well such as https://github.com/Darkosto/SevTech-Ages/issues/415. Not really sure who is to blame for that.

If I recall correctly, Buildcraft was updated between the two alphas.

**Comment by Darkhax** [comment]
Repositing image here for reference. 
![image](https://user-images.githubusercontent.com/30686588/34658213-0c34b9be-f3e2-11e7-9025-36956fd7f717.png)

**Comment by justinrusso** [comment]
Seems to me like its not related to this mod at all. From any example I've seen, the item appears to be providing the wrong item to WAILA, which that item is restricted by Item Stages and thus appears as "Restricted Item". For example, in that reference image, the item that is according to WAILA is a Diamond Pipe, which to the player is restricted at that point.

**Comment by Darkhax** [comment]
Thanks for the update. Hopefully they can fix that up.
