### ISSUE TITLE
Sugestion: TOP And TOP Addons Integration

### ISSUE THREAD

**Issue by CTH999** [Darkhax-Minecraft/WailaStages#2]
It's integrated with Hwyla, but what happened to [The One Probe](https://minecraft.curseforge.com/projects/the-one-probe) and it's [Compatibility add-on](https://minecraft.curseforge.com/projects/top-addons?gameCategorySlug=mc-mods&projectID=247111) Top Addons?

I think this mod should have integration with these mods To. (Just a suggestion)

**Comment by Darkhax** [comment]
Support for TOP has been discussed. I will probably be releasing it soon, just need to test things.

**Comment by CTH999** [comment]
Thanks!

**Comment by Ethryan** [comment]
Any progress on this?

**Comment by Darkhax** [comment]
The one probe is too dissimilar to Hwyla, meaning a new mod would need to be created to add support for everything. There are currently no plans to do this.
